name: ecowave
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_bloc: ^8.1.2
  get_it: ^7.6.0
  intl: ^0.18.1
  another_flushbar: ^1.12.30
  lottie: ^2.3.2
  carousel_slider: ^4.2.1
  flutter_countdown_timer: ^4.1.0
  flutter_rating_bar: ^4.0.1
  file_picker: ^5.3.1
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  dio: ^5.1.2
  equatable: ^2.0.5
  flutter_html: ^3.0.0-beta.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_app.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
