// Mocks generated by Mockito 5.4.2 from annotations
// in ecowave/test/features/payment/model/services/expedition_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ecowave/features/payment/model/models/expedition_model.dart'
    as _i4;
import 'package:ecowave/features/payment/model/models/expedition_request.dart'
    as _i5;
import 'package:ecowave/features/payment/model/services/expedition_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ExpeditionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpeditionService extends _i1.Mock implements _i2.ExpeditionService {
  MockExpeditionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ExpeditionModel>> getExpeditions(
          _i5.ExpeditionRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExpeditions,
          [request],
        ),
        returnValue: _i3.Future<List<_i4.ExpeditionModel>>.value(
            <_i4.ExpeditionModel>[]),
      ) as _i3.Future<List<_i4.ExpeditionModel>>);
}
